server:
  port: 8080
spring:
  application:
    name: userdetail
  profiles:
    active: default
  cloud:
    config:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://hoteldiscovery.appspot.com/eureka/