server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: default
  cloud:
    config:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://discovery-259910.appspot.com/eureka/

zuul:
  ignored-services: '*'
  routes:
    hotelroomdetail:
      path: /hotelroomdetail/**
      sensitiveHeaders:
      url: https://hotelservice.appspot.com
    userdetail:
      path: /userdetail/**
      sensitiveHeaders:
      url: https://user-259905.appspot.com
    booking:
      path: /booking/**
      sensitiveHeaders:
      url: https://bookingservice-260006.appspot.com
    authservice:
      path: /authservice/**
      sensitiveHeaders:
      url: https://authservice-259910.appspot.com