server:
  port: 9000
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: '*'
  routes:
    hotelroomdetail:
      path: /hotelroomdetail/**
      sensitiveHeaders:
    userdetail:
      path: /userdetail/**
      sensitiveHeaders:
    booking:
      path: /booking/**
      sensitiveHeaders:
    authservice:
      path: /authservice/**
      sensitiveHeaders: