server:
  port: 8080
spring:
  application:
    name: hotelroomdetail
  profiles:
    active: default
  cloud:
    config:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
    home-page-url: https://hotelservice.appspot.com
    hostname: https://hotelservice.appspot.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://discovery-259910.appspot.com/eureka/